import { iConcatOptions, iConcatResults } from './interfaces';
export declare type iConcatOptions = iConcatOptions;
export declare class ConcatScss {
    private insertIntoString;
    private getIndexPathInsideDirectory;
    private getAllPossibleImportPaths;
    private iterateLinesInFile;
    private resetState;
    private setRemoveImports;
    private compileSass;
    private addAutoGeneratedComment;
    private writeOutput;
    concat(options: iConcatOptions): Promise<iConcatResults>;
}
